wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1633722645
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      3:
      - 13
      4: 3.7.7
      5: 0.12.4
      6: 4.11.3
      8:
      - 5
