wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1633631250
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      3:
      - 13
      4: 3.7.7
      5: 0.12.4
      6: 4.11.3
      8:
      - 5
adam_epsilon:
  desc: null
  value: 1.0e-08
dev_data:
  desc: null
  value: example_data/dev.json
early_stop_callback:
  desc: null
  value: false
eval_batch_size:
  desc: null
  value: 8
fp_16:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 1.0
max_seq_length:
  desc: null
  value: 512
model_name_or_path:
  desc: null
  value: t5-base
model_type:
  desc: null
  value: T5
n_gpu:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 10
opt_level:
  desc: null
  value: '01'
output_ckpt_dir:
  desc: null
  value: T5/ckpt/
random_state:
  desc: null
  value: 42
seed:
  desc: null
  value: 42
test_data:
  desc: null
  value: example_data/test.json
tokenizer_name_or_path:
  desc: null
  value: t5-base
train_batch_size:
  desc: null
  value: 8
train_data:
  desc: null
  value: example_data/train.json
use_tpu:
  desc: null
  value: false
wandb_name:
  desc: null
  value: T5
wandb_project:
  desc: null
  value: In-the-wild-VQA
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
